[package]
name = "nbt-string-replacer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
fastnbt = "2.5"
flate2 = "1.0"
walkdir = "2.5"
